name: chat_gpt_client_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  path: ^1.9.0
  provider: ^6.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  static_analyze_av: ^0.2.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
